// Generated by CoffeeScript 2.0.0-beta4
var WebSocket;

WebSocket = require('ws');

Poltergeist.Connection = class Connection {
  constructor(owner, port, host = "127.0.0.1") {
    this.commandReceived = this.commandReceived.bind(this);
    this.owner = owner;
    this.port = port;
    this.host = host;
    this.socket = new WebSocket(`ws://${this.host}:${this.port}/`);
    this.socket.onmessage = this.commandReceived;
    this.socket.onclose = () => {
      return this.owner.browser.browser.close();
    };
  }

  commandReceived(message) {
    return this.owner.runCommand(JSON.parse(message.data));
  }

  send(message) {
    return this.socket.send(JSON.stringify(message));
  }

};
